/**
 * Migration to create the 'virtual_accounts' table.
 *
 * @param { import("knex").Knex } knex - The Knex instance for database schema operations.
 * @returns { Promise<void> } A promise that resolves when the table is created.
 */
exports.up = function(knex) {
  return knex.schema.createTable('virtual_accounts', table => {
    table.uuid('id').primary(); // Primary key for the virtual account (UUID)
    
    table.uuid('user_id')
      .notNullable()
      .references('id')
      .inTable('users')
      .onDelete('CASCADE'); // Foreign key to 'users' table, deletes VA when user is deleted

    table.string('account_number').notNullable(); // The virtual account number (e.g. generated by bank)
    table.string('account_name').notNullable();   // The display name associated with the account
    table.string('bank_name').notNullable();      // The bank providing the virtual account

    table.timestamps(true, true); // Adds created_at and updated_at with default current timestamp
  });
};

/**
 * Rollback migration: Drop the 'virtual_accounts' table if it exists.
 *
 * @param { import("knex").Knex } knex - The Knex instance for database schema operations.
 * @returns { Promise<void> } A promise that resolves when the table is dropped.
 */
exports.down = function(knex) {
  return knex.schema.dropTableIfExists('virtual_accounts');
};
